[aws]
symbol = "  "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

#[golang]
#format = "[ $version] (bold cyan)"
# ~/.config/starship.toml

[golang]
format ="[ $version](bold cyan)"

[hg_branch]
symbol = " "

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
[hostname]
ssh_symbol = " "

[java]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "
